version: "3"

services:
  app:
    image: snaksa/spotify-downloader-nodejs
    build:
      context: .
    container_name: spotify-nodejs
    volumes:
     - ./server.js:/usr/src/app/server.js
    ports:
      - "9090:8080"
